### ISSUE TITLE
Expose Pioneer Projects on main website

### ISSUE THREAD

**Issue by amirmc** [mirage/mirage-www#270]
At a minimum we should link to the wiki page but it would be cool if we could incorporate the content directly into the website.

(meta: maybe this should be a pioneer project?)

**Comment by marklrh** [comment]
It would be really easy if we can figure out a way to get the markdown text of that wiki page.

**Comment by amirmc** [comment]
GitHub wikis are also git repos themselves and the pages are actually markdown already. 

Append '.wiki' to the main repo name and you get the git repo of the wiki (if that makes sense).

**Comment by marklrh** [comment]
I found the [raw link](https://raw.githubusercontent.com/wiki/mirage/mirage-www/Pioneer-Projects.md)

**Comment by marklrh** [comment]
but I am not sure where we want to place this pioneer project link

**Comment by avsm** [comment]
There's a contributions page that it could go into -- and that page can go on the front page somewhere or the menu.

**Comment by marklrh** [comment]
@amirmc I am not experienced with Mirage's design but I am studying it. Since we have the link to the wiki, I suppose we want to write a function like [read_tmpl](https://github.com/mirage/mirage-www/blob/master/src/dispatch.ml#L11) such that given the a http link (rather than a filesystem path), it can return its content as ``string Lwt.t``. Then, I guess we also need a ``Cohttp.Client`` for ``module Main`` so that we can get the content associated with the link?

**Comment by hannesm** [comment]
On https://mirage.io/community/ below "The community", second paragraph, links to contribution guide and our pioneer projects. closing this issue, if you feel it should be linked more, please open a PR :)
