### ISSUE TITLE
Fix the 'Disk full' issues on the server (punk)

### ISSUE THREAD

**Issue by amirmc** [mirage/mirage-www#379]
@samoht noticed that the disk was full again, which prevent the automated deployment of the new unikernel.  Apparently this is the second time it's happened so we should put a fix in place.

**Comment by mor1** [comment]
Had to fix that a couple of days ago to be able to restart my site too, and for latest mirage-www to be booted.

Fixes that spring to mind: make the disk bigger (not really a long-term fix); simply delete all the unikernel images apart from `$(cat latest)` from the the checked out commit-rev; compress and garbage collect history, removing old built unikernels from history. Basically we need a policy for managing garbage collection. Perhaps this ought to be implemented in Irmin so we can define smarter merge and history management functions, and *really* automate deployment rather than relying on the `post-merge.hook` hack.

**Comment by avsm** [comment]
An update: it turns out that there's a 500GB unused LVM group there.  I created a `/home` volume and am rsyncing the existing `/home` into that, and will do the swapover when complete. This will stop `/home` from existing on the root disk and fix this immediate issue.

**Comment by yomimono** [comment]
If we still need to do maintenance on punk, let's open a new and more specific issue with a plan of action that makes sense in the current universe.
