### ISSUE TITLE
Please update to ocaml 4.07.0

### ISSUE THREAD

**Issue by KenDickey** [mirage/mirage-www#619]
Greetings,

I have been playing with mirage-skeleton, got applications/static_website_tls working (hvt/RPi3/ArchLinuxArm) and thought to try it with mirage-www.

It appears this is somewhat dated (see below).

Can some kind person email me when the code is updated for the current ocaml release?

Thanks much,
-KenD  [ Ken (dot) Dickey (at) Whidbey (dot) com ]

[make-prepare.txt](https://github.com/mirage/mirage-www/files/2503739/make-prepare.txt)

**Comment by mato** [comment]
@KenDickey Yes, the `mirage-www` stack is currently stuck on 4.05.0 due to the Xen platform stack only supporting OCaml <= 4.05.0. This should change by the end of the year with a refreshed Xen platform stack which is in progress.

Having said that, the tooling and general design of `mirage-www` is really in need of an overhaul, so I wouldn't bother with it as something to learn from.

**Comment by avsm** [comment]
mirage-xen does now work on 4.07, but the rrd library is holding us back.  I'll take a look at that next...
